### PR TITLE
Fixes Deprecation Warnings

### LINKED ISSUE #15: Deprecation Warnings
We are now experiencing deprecation warnings.

```
DEPRECATION WARNING: You are using the a deprecated processor interface Sprockets::CoffeeReact.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from configure_env at /Users/craigs/.rvm/gems/ruby-2.2.5/gems/sprockets-coffee-react-4.0.0/lib/sprockets/coffee-react/engine.rb:18)
DEPRECATION WARNING: You are using the a deprecated processor interface Sprockets::CoffeeReactPostprocessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from configure_env at /Users/craigs/.rvm/gems/ruby-2.2.5/gems/sprockets-coffee-react-4.0.0/lib/sprockets/coffee-react/engine.rb:19)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from configure_env at /Users/craigs/.rvm/gems/ruby-2.2.5/gems/sprockets-coffee-react-4.0.0/lib/sprockets/coffee-react/engine.rb:20)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from configure_env at /Users/craigs/.rvm/gems/ruby-2.2.5/gems/sprockets-coffee-react-4.0.0/lib/sprockets/coffee-react/engine.rb:21)
```

Current gems are ...

- coffee-react: 4.0.0
- rails: 4.2.7
- react-rails: 1.8.0
- ruby: 2.2.5
- sprockets: 3.7.0
- sprockets-coffee-react: 4.0.0
- sprockets-rails: 3.1.1

Happy to have a crack at a PR if there are no active devs on the project.

### PR DESCRIPTION
**Pull request by raelgc**
Fixes #15

### CODE REVIEW

**Comment by raelgc** [comment]
@jsdf Please, review :)

**Comment by xijo** [comment]
@raelgc Thanks for this pull request.

Unfortunately using your branch caused an `ActionView::Template::Error ("\xC3" from ASCII-8BIT to UTF-8)` within my application. Please tell me which details you'd need to track that down!

**Comment by raelgc** [comment]
@xijo Thanks for the feedback!

Sounds like your app is using some non `UTF-8` files. Any idea of which one (so you can upload a sample)?

The stack trace will help too!

**Comment by xijo** [comment]
@raelgc Looked for non-utf8 files with `git ls-files | xargs -I XXX bash -c "iconv -f utf-8 -t utf-16 XXX &>/dev/null || echo XXX"` - but there were only image files.

The stacktrace is not particularly helpful, it points to the first include code of application.js or application.css (I tried commenting them out). That's all!

```
app/views/layouts/_head.html.slim:8:in `_app_views_layouts__head_html_slim___1375615630663473497_70227150277700'
  app/views/layouts/application.html.slim:12:in `_app_views_layouts_application_html_slim__1357735668221712467_70227245189460'
```

I found the problem by downgrading the gem back to the original jsdf-version, just by wild-guessing.. :/

**Comment by raelgc** [comment]
In a quick search through the web, sounds like rails trying handle binary
files as ascii.

Em 3 de set de 2016 9:52 AM, "Johannes Opper" <notifications@github.com>
escreveu:

@raelgc <https://github.com/raelgc> Looked for non-utf8 files with git
ls-files | xargs -I XXX bash -c "iconv -f utf-8 -t utf-16 XXX &>/dev/null
|| echo XXX" - but there were only image files.

The stacktrace is not particularly helpful, it points to the first include
code of application.js or application.css (I tried commenting them out).
That's all!

app/views/layouts/_head.html.slim:8:in
`_app_views_layouts__head_html_slim___1375615630663473497_70227150277700'
  app/views/layouts/application.html.slim:12:in
`_app_views_layouts_application_html_slim__1357735668221712467_70227245189460'

I found the problem by downgrading the gem back to the original
jsdf-version, just by wild-guessing.. :/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jsdf/sprockets-coffee-react/pull/16#issuecomment-244544688>,
or mute the thread

**Comment by raelgc** [comment]
@xijo In original version (i.e., without my PR), it works fine?

**Comment by xijo** [comment]
@raelgc yes it does

**Comment by raelgc** [comment]
@xijo And this breaks your app? Or just an output in console?

**Comment by xijo** [comment]
It throws the `ActionView::Template::Error`, so it results in an app-500

**Comment by raelgc** [comment]
@xijo Thanks for sharing all this info.

I just tried to add `# encoding: utf-8` to all files to suggest the file encoding.

**Comment by raelgc** [comment]
Another question: these image files, they're just required in the HTML/ERB files?

**Comment by keithpitt** [comment]
I've just tried this branch out locally, worked like a treat!

👍

**Comment by keithpitt** [comment]
Actually..I'm getting encoding errors as well:

`ActionView::Template::Error ("\xE2" from ASCII-8BIT to UTF-8):`

Oddly enough I'm seeing this error generated from this line of HAML:

```ruby
= stylesheet_link_tag "public", "public_fonts", media: "all"
```

Which is including our stylesheet and fonts...

Let me know if there's any data I can provide!

**Comment by raelgc** [comment]
@keithpitt: thank you for the feedback! Let's get this solved! :)

Sounds like any of these CSS are using a non `UTF-8` char. Probably a good way to solve this will be force a encode converter in this library.

Can you, please, paste the stack here? So I can see in which line this is raised.

**Comment by raelgc** [comment]
@keithpitt A better idea: can you reduce your CSS to just one file able to reproduce this issue? So you can send me and I can investigate it.

**Comment by raelgc** [comment]
Appears that I can't get a sample from anyone :(

**Comment by xijo** [comment]
@raelgc Sorry dude! I just tried it again and it does seem to be working atm, so I couldn't reproduce the error. I'll stay on your branch for a while and see if I can get it again.

From my memory: it didn't matter whether you actually included a file or not, even if you skipped the whole include part it still used to throw the error - that's not very helpful, I know, but that's what happened :) I'll keep you up-to-date.

**Comment by raelgc** [comment]
@xijo Thank you for the feedback! :+1:

**Comment by raelgc** [comment]
@jsdf Can you give any feedback on this? Is this gem abandoned?

**Comment by keithpitt** [comment]
@raelgc will try and make a sample now!

**Comment by keithpitt** [comment]
So I couldn't make an example app (I haven't had enough ☕ today and my brain isn't working), but I did manage to track down a repeatable way of having the error thrown!

Given this CoffeeScript file:

```
# 👋
```

It throws this error:

```
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `encode'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
execjs (2.7.0) lib/execjs/external_runtime.rb:46:in `call'
coffee-react (4.0.0) lib/coffee_react.rb:37:in `transform'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/sprockets-coffee-react-d0d221f60200/lib/sprockets/coffee-react.rb:28:in `run'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/sprockets-coffee-react-d0d221f60200/lib/sprockets/coffee-react.rb:23:in `call'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.0) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.0) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.0) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.7.0) lib/sprockets/utils.rb:196:in `dfs'
sprockets (3.7.0) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.7.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.7.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.7.0) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.7.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.7.0) lib/sprockets/loader.rb:44:in `load'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.7.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.7.0) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.7.0) lib/sprockets/base.rb:73:in `find_all_linked_assets'
sprockets (3.7.0) lib/sprockets/manifest.rb:142:in `block in find'
sprockets (3.7.0) lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
sprockets (3.7.0) lib/sprockets/path_utils.rb:228:in `block in stat_tree'
sprockets (3.7.0) lib/sprockets/path_utils.rb:212:in `block in stat_directory'
sprockets (3.7.0) lib/sprockets/path_utils.rb:209:in `each'
sprockets (3.7.0) lib/sprockets/path_utils.rb:209:in `stat_directory'
sprockets (3.7.0) lib/sprockets/path_utils.rb:227:in `stat_tree'
sprockets (3.7.0) lib/sprockets/legacy.rb:105:in `each'
sprockets (3.7.0) lib/sprockets/legacy.rb:105:in `block in logical_paths'
sprockets (3.7.0) lib/sprockets/legacy.rb:104:in `each'
sprockets (3.7.0) lib/sprockets/legacy.rb:104:in `logical_paths'
sprockets (3.7.0) lib/sprockets/manifest.rb:140:in `find'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `each'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `map'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:50:in `precompiled_assets'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:35:in `asset_precompiled?'
sprockets-rails (3.2.0) lib/sprockets/railtie.rb:251:in `block (3 levels) in <class:Railtie>'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:359:in `precompiled?'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:363:in `raise_unless_precompiled_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:348:in `find_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:229:in `block in lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `each'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `detect'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:241:in `resolve_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:228:in `lookup_debug_asset'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:170:in `block in stylesheet_link_tag'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in `map'
sprockets-rails (3.2.0) lib/sprockets/rails/helper.rb:169:in `stylesheet_link_tag'
app/views/layouts/application.html.erb:7:in `_app_views_layouts_application_html_erb__4419481160342163402_70229824324520'
actionview (5.0.0.1) lib/action_view/template.rb:158:in `block in render'
activesupport (5.0.0.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.0.0.1) lib/action_view/template.rb:348:in `instrument'
actionview (5.0.0.1) lib/action_view/template.rb:156:in `render'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (5.0.0.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.0.0.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.0.0.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.0.0.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.0.0.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.0.0.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.0.0.1) lib/action_controller/metal/renderers.rb:144:in `render_to_body'
actionpack (5.0.0.1) lib/abstract_controller/rendering.rb:26:in `render'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.0.0.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.0.0.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.0.0.1) lib/action_controller/metal/implicit_render.rb:36:in `default_render'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.0.1) lib/active_record/migration.rb:552:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
web-console (3.3.1) lib/web_console/middleware.rb:131:in `call_app'
web-console (3.3.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.3.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
puma (3.6.0) lib/puma/configuration.rb:225:in `call'
puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
puma (3.6.0) lib/puma/server.rb:415:in `process_client'
puma (3.6.0) lib/puma/server.rb:275:in `block in run'
puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by raelgc** [comment]
Thank you @keithpitt! I'll investigate now! :)

**Comment by keithpitt** [comment]
No worries! If you need any more info let me know!

**Comment by raelgc** [comment]
@keithpitt Two interesting notes:

1. If I remove all my changes, I still will see the same error.
2. If I try to enforce the encoding to `UTF-8` in the `transform` method call, this will cause a routing error and the page will become blank (no idea the reason).

**Comment by keithpitt** [comment]
Hrm...#1 is weird since if I use the latest stable version of `sprockets-coffee-react` I don't get the error, it's only when I use this:

```
gem 'sprockets-coffee-react', github: "raelgc/sprockets-coffee-react"
```

**Comment by raelgc** [comment]
Thank you for the feedback @keithpitt. I just tried to revert changes locally instead of point to the former gem. As this involves force reload (changing any code in the JSX file, then restart rails), probably I missed something.

**Comment by raelgc** [comment]
If I restore the registration of the processor to the old:

```ruby
            environment.register_engine '.cjsx', Sprockets::CoffeeReactScript
            environment.register_engine '.js.cjsx', Sprockets::CoffeeReactScript
```

It'll work. If I use the new:

```ruby
          environment.register_mime_type 'application/javascript', extensions: ['.cjsx'], charset: :javascript
          environment.register_mime_type 'application/javascript', extensions: ['.js.cjsx'], charset: :javascript
```

It'll raise the error.

**Comment by raelgc** [comment]
Wow, which leads to the obvious reason: emoji is not allowed in JS (I'm using `charset: :javascript`). If I use `UTF-8`, it works!

**Comment by raelgc** [comment]
Ok, here we go, guys! Can you, please, test it now again?

**Comment by raelgc** [comment]
Guys, as I have no answer from @jsdf I'm tempted to close this PR and keep working in the fork.

**Comment by raelgc** [comment]
Ok guys, due no owner answer, I'll try create a new gem. So I'm closing this PR for now.

**Comment by keithpitt** [comment]
@raelgc do let me know the new gem and I'll switch across :)

**Comment by raelgc** [comment]
@keithpitt Finally: https://github.com/raelgc/sprockets-coffee-jsx

**Comment by keithpitt** [comment]
Woo!

**Pull request closed without merging**
